spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yg?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  #扫描 classpath 中 mapper 目录下的映射配置文件，针对于映射配置文件放到了 resources 目录下
  mapper-locations: classpath:/mapper/*.xml
  #定义包别名，使用 pojo 时可以直接使用 pojo 的类型名称不用加包名
  type-aliases-package: com.bjsxt.springbootmybatis.pojo

